[package]
name = "robson_compiler"
version = "0.1.5"
edition = "2021"
description = "Dependency of the robson cli"
license = "MIT"
repository = "https://github.com/gabireugabiru/RobsonCompiler"
homepage = "https://robson.fly.dev"
[dependencies]
rand = "0.8.5"
crossterm = "0.23.2"
